### ISSUE TITLE
Move secret

### ISSUE THREAD

**Issue by kruemmelkhanh** [DCI-fbw11/bookmark-api#100]
Move secret into a separate file

**Comment by sit79** [comment]
I suggest storing secret in an environment variable, to avoid exposing it accidentally. Cf. https://hackernoon.com/how-to-use-environment-variables-keep-your-secret-keys-safe-secure-8b1a7877d69c

**Comment by kruemmelkhanh** [comment]
> I suggest storing secret in an environment variable, to avoid exposing it accidentally. Cf. https://hackernoon.com/how-to-use-environment-variables-keep-your-secret-keys-safe-secure-8b1a7877d69c

will have a look at it later

**Comment by sit79** [comment]
solved with dotenv
