### ISSUE TITLE
add logout endpoint

### ISSUE THREAD

**Issue by martynakrysinska** [DCI-fbw11/bookmark-api#123]
users can't logout

**Comment by xqwtsz** [comment]
> users can't logout

[they can't](https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6) 🤓

![one](https://cdn-images-1.medium.com/max/1600/1*Qp_2RBl4GgCn022OZFpkfQ.jpeg)

**Comment by martynakrysinska** [comment]
> > users can't logout
> 
> [they can't](https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6) 🤓
> 

yep, read that article on wednesday, i guess we're gonna leave it the way it is ?

**Comment by kruemmelkhanh** [comment]
> > > users can't logout
> > 
> > 
> > [they can't](https://medium.com/devgorilla/how-to-log-out-when-using-jwt-a8c7823e8a6) 🤓
> 
> yep, read that article on wednesday, i guess we're gonna leave it the way it is ?

yeah let the frontend handle this 🙈 🙉 🙊
