### ISSUE TITLE
Unify documentation

### ISSUE THREAD

**Issue by sit79** [DCI-fbw11/bookmark-api#160]
API doc section in `README.MD` and `docs/DOCS.MD` should have the same content. It makes sense to have `README.MD` contain a little more info in the beginning, since it is aimed at GitHub users.

**Comment by xqwtsz** [comment]
README.md is for the class/developers of the API, DOCS.md is for the API users.

But I get what you're saying. Our current README.md has still lowDB references and needs to be updated.
