### ISSUE TITLE
Use dates with timezone

### ISSUE THREAD

**Issue by Bilie** [DCI-fbw11/bookmark-api#25]
Currently the bookmark uses date in milliseconds, update the model to use date that stores timezone info.
Time is relative

**Comment by sit79** [comment]
Timezones might be a tricky issue with JavaScript. I read a bit on it [here](https://medium.com/@toastui/handling-time-zone-in-javascript-547e67aa842d).

**Comment by sit79** [comment]
[Moment Timezone](https://momentjs.com/timezone/) is a library that might help, if someone wants to look into this.
