### ISSUE TITLE
Add API documentation

### ISSUE THREAD

**Issue by Bilie** [DCI-fbw11/bookmark-api#58]
Add (generate) documentation for each endpoint, the input it expects and the values it returns

**Comment by kruemmelkhanh** [comment]
Pictures i used 
![all_routes](https://user-images.githubusercontent.com/44833666/57297961-446d4b80-70d1-11e9-9ca9-b30f2ecb9d4a.png)

![all_success](https://user-images.githubusercontent.com/44833666/57299736-a5971e00-70d5-11e9-99b7-8723f285f7cc.png)

![all_error](https://user-images.githubusercontent.com/44833666/57298353-45eb4380-70d2-11e9-9229-01cde10990dd.png)

![success_by_id](https://user-images.githubusercontent.com/44833666/57299768-b6479400-70d5-11e9-809c-0ae829f4c74f.png)

![error_by_id](https://user-images.githubusercontent.com/44833666/57299793-cc555480-70d5-11e9-8fd6-21ffc7f07723.png)

![success_post](https://user-images.githubusercontent.com/44833666/57299804-d24b3580-70d5-11e9-8732-ea95d0c9968f.png)

![error_post](https://user-images.githubusercontent.com/44833666/57299806-d5debc80-70d5-11e9-93d8-e28ee1e29a36.png)

![success_update](https://user-images.githubusercontent.com/44833666/57299823-dbd49d80-70d5-11e9-8549-1f73f893d03a.png)

![error_update](https://user-images.githubusercontent.com/44833666/57299837-df682480-70d5-11e9-9183-95a253fe81af.png)

![success_delete](https://user-images.githubusercontent.com/44833666/57299855-e5f69c00-70d5-11e9-8dcf-009d8aa2ccd1.png)

![error_delete](https://user-images.githubusercontent.com/44833666/57299867-e98a2300-70d5-11e9-940e-ef0b24a13a6c.png)
