### ISSUE TITLE
Refactor code into Async/Await

### ISSUE THREAD

**Issue by kruemmelkhanh** [DCI-fbw11/bookmark-api#74]
Refactor the code so it's used Async/Await

**Comment by sit79** [comment]
Why?!

**Comment by kruemmelkhanh** [comment]
I think it is easier to read than the chain of .then. But it was more of a suggestion if the majority wants to keep then I am also ok with it

**Comment by martynakrysinska** [comment]
i think it's a good idea and i'd like to refactor couple of functions

**Comment by ctocco** [comment]
const router = require('express-promise-router')() will write for you try catch ... block
also trying this out as recommended by @cino! This means in the future we do not need to write try catch with our async awaits
