### ISSUE TITLE
Tag unique Issue

### ISSUE THREAD

**Issue by kruemmelkhanh** [DCI-fbw11/bookmark-api#78]
The Tags are unique in the whole database instead of just the Tags-Array.

**Comment by martynakrysinska** [comment]
hi Khanh, it was my ticket! i'm not sure what you mean with the "whole database", could you please share more details about the bug?

**Comment by martynakrysinska** [comment]
i took a look and yeah, we definitely have a bug here.
i get "Wrong ID please enter a valid ID" when i'm trying to add duplicate tags 
things have changed since my commit and now the branch is on fire
