### ISSUE TITLE
Update Tag maybe a bug?

### ISSUE THREAD

**Issue by kruemmelkhanh** [DCI-fbw11/bookmark-api#92]
When you update a tag it will override all the existing tag.
Do we want to change it so it adds a tag?

**Comment by martynakrysinska** [comment]
sure, i'm on it now

**Comment by martynakrysinska** [comment]
so i've been thinking about this issue and maybe that's something that should be solved on the front-end?

for now if we want to update an array of tags, we have to pass the whole updated array in our req.body, not just the elements we want to add and maybe that's the behaviour we actually want (consider deleting tags)

**Comment by xqwtsz** [comment]
@kruemmelkhanh @martynakrysinska 
API users will need to send the whole new edited object back, which includes the unedited object fields as well. I think the confusion comes from what these tickets were originally opened for before, a social bookmarking app. 
So as Martyna said for the update process we __WILL__ expect the whole edited object.
